### ISSUE TITLE
Caffeena

### ISSUE THREAD

**Issue by Emtenan1** [fewd-puffin/final-project#10]
**Name of website:** 
Coffeena
**What the website does:** 
It's a website of a coffee shop that contain some information about the brand and the services  provided by the coffee shop.
**Who's the target of the website:** 
any person who interested in tasting an exceptional coffee
**Link of the website:** 
https://share.protopie.io/bb9iYU6eSea
**any predicted problem:**
I think I will facing some issues in how to style the pages, but I'm here to learn.

**Comment by JackieCasper** [comment]
Hi Emtenan,
It sounds like a good idea but I can't see your wireframes! All I see is a screen that says "Hello". Could you upload some photos?

**Comment by Emtenan1** [comment]
Dear Jackie,

I'm sorry about that. This is my wireframe

https://www.figma.com/file/W7PHLSY93GKs7vFPagN0D4yc/Untitled?node-id=0%3A1


Thank you,
________________________________

**Comment by JackieCasper** [comment]
Hello again!

This is going in a good direction. Since this is a front end class we will not be covering features that require a backend such as booking appointments or sending emails. Could you do more of an informational page on the coffee brand and maybe a contact that would have a link for emailing?

**Comment by Emtenan1** [comment]
Yes, I will try it.

On 12 Apr 2019, at 1:15 PM, Jackie Casper <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello again!

This is going in a good direction. Since this is a front end class we will not be covering features that require a backend such as booking appointments or sending emails. Could you do more of an informational page on the coffee brand and maybe a contact that would have a link for emailing?

**Comment by JackieCasper** [comment]
Great 👍 looking forward to seeing it!
