### ISSUE TITLE
Minerals

### ISSUE THREAD

**Issue by razan1** [fewd-puffin/final-project#12]
Name of your website: **Minerals.**

What your website does: My website have header and 8 sections.
All of the sections have link to go other page has paragraph in middle.
section (1,3,5,7) has text (background image) on the left and different text on the right.
section (2,4,6,8) is reverse other section { 1,3,5,7 } .

who your website is for: **All of the people.**
links to your wireframe: https://www.figma.com/file/Jbei5zmsW4HBe7WTC6yoA7es/Minerals?node-id=0%3A1

Any predicted problem/hard things you see/things you still need to learn: Size

**Comment by trevorpreston** [comment]
Hey Razan,

Could you describe the purpose of your site?  Is it displaying information about something?  Is it a game?  Some more details would be helpful.

Approval pending

**Comment by razan1** [comment]
My website displaying information about Minerals.

**Comment by razan1** [comment]
I'm terribly sorry for being late I just saw your message before few minutes.

**Comment by trevorpreston** [comment]
No worries!  I understand now, and it all sounds good.  Looking forward to the draft tomorrow!
