### ISSUE TITLE
Green Grocery

### ISSUE THREAD

**Issue by zeina15** [fewd-puffin/final-project#13]
Green Grocery
store website provides organic and healthy products.
for people they concern about healthy food and fitness.
wirefram: https://www.figma.com/file/Qq3rmuBcfCZkGRxiG807J7CY/Untitled?node-id=0%3A1
problems: style for products and details of products.

**Comment by trevorpreston** [comment]
Hi Zainah,

I like the idea.  One thing to be aware of - we won't be covering users or password storage, that requires a backend.   The best we can do is do a fake login where there are no passwords - any user can click "login" and it would work.  Same goes for the cart.  Is that ok?  

Let me know if that works for you!

**Comment by zeina15** [comment]
I know how to do log in page by Js and php but it is ok I will learn how to make it fake.
Thanks a lot.

**Comment by trevorpreston** [comment]
Sounds good, looking forward to it!
