### ISSUE TITLE
Eracure 

### ISSUE THREAD

**Issue by sara-daghustani** [fewd-puffin/final-project#14]
name of your website: Eracure
what your website does:
Contain information of Eracure app and a link to download it.
Eracure is an application where you can request physical therapy to your home. 
who your website is for:
people who are looking for physical therapy.
links to your wireframe/prototype: (https://github.com/fewd-puffin/final-project/files/3066039/sara.pdf)
any predicted problems/hard things you see/things you still need to learn:
javascript

**Comment by JackieCasper** [comment]
👍 👍 Approved. The only thing I would say is we will not be covering how to do authentication so the "sign up" feature would not be possible. Otherwise, this looks great!
