### ISSUE TITLE
My Portfolio

### ISSUE THREAD

**Issue by shumukh77** [fewd-puffin/final-project#15]
1. name of your website: Shumukh's Portfolio
2. what your website does: An online portfolio to showcase my work and projects with a theme that match my style. It'll be fully personalized to my aesthetics and will also prove my front-end development skills.
3. who your website is for: companies and agencies who are looking for a graphic designer and individuals who are looking for a freelance designer or graphic design project inspirations.
4. links to your wireframe/prototype: https://www.figma.com/file/DwYUYArgN3unfeLodA2zaZti/Portfolio-Website?node-id=0%3A1
5. any predicted problems/hard things you see/things you still need to learn: animation and javascript.

**Comment by trevorpreston** [comment]
This is a solid start!  Can you add wireframes for the "about me", "contact" and "projects" pages?  Once we have those I can approve this.

**Comment by shumukh77** [comment]
Hi Trevor. 
I tried to reach you on Slack but maybe it's better to comment back in here. I did wireframe for the entire website but I don't know why Figma did not show the other sections on your computer. I tried clicking on the link and all the pages appeared (not just the home page). So I will send screenshots of wireframes.
<img width="1680" alt="Screen Shot 2019-04-11 at 9 02 11 PM" src="https://user-images.githubusercontent.com/49195311/55980921-3aa52380-5c9e-11e9-943d-117aafb44fab.png">
<img width="881" alt="Screen Shot 2019-04-11 at 9 02 14 PM" src="https://user-images.githubusercontent.com/49195311/55980941-442e8b80-5c9e-11e9-91d1-dba988ef7add.png">
<img width="847" alt="Screen Shot 2019-04-11 at 9 02 33 PM" src="https://user-images.githubusercontent.com/49195311/55980946-48f33f80-5c9e-11e9-985e-c0499caf10fb.png">
<img width="351" alt="Screen Shot 2019-04-11 at 9 03 10 PM" src="https://user-images.githubusercontent.com/49195311/55980950-4b559980-5c9e-11e9-9c01-098898a161b3.png">
<img width="1190" alt="Screen Shot 2019-04-11 at 9 03 34 PM" src="https://user-images.githubusercontent.com/49195311/55980954-4e508a00-5c9e-11e9-8bcf-c3d25d57e5df.png">
<img width="350" alt="Screen Shot 2019-04-11 at 9 03 21 PM" src="https://user-images.githubusercontent.com/49195311/55980956-4e508a00-5c9e-11e9-9823-0e0f4168b0c1.png">

and here's the link again, it might work this time: https://www.figma.com/file/DwYUYArgN3unfeLodA2zaZti/Portfolio-Website?node-id=1%3A2

**Comment by shumukh77** [comment]
Each wireframe is on a separate page.
<img width="200" alt="Screen Shot 2019-04-11 at 9 02 11 PM" src="https://user-images.githubusercontent.com/49195311/55981389-39c0c180-5c9f-11e9-9c15-afd0ea3ac9c8.png">

**Comment by trevorpreston** [comment]
looks excellent!  Approved 👍
