### ISSUE TITLE
cupcake wireframe

### ISSUE THREAD

**Issue by Raghad999** [fewd-puffin/final-project#16]
-name of your website: Lora's cupcake.
-what your website does: 
My website is a cupcake shop website , it is like marketing website.it has 3 main pages which are about us ,menu and contact us. The first page is about us , it shows information about the shop like when it starts and who is the owner of the shop and etc.the second page is a menu page ,it shows the cupcakes that we made and the description about each cupcake.the last page is contact us , it shows the contact information.

-who your website is for: for anyone who loves cupcake
-link to your wireframe:
https://www.figma.com/file/FYBwd5KME9Fn7CkVdnjRcmtw/Untitled?node-id=0%3A1
-any predicted problems/hard things you see/things you still need to learn: 
no

**Comment by JackieCasper** [comment]
👍 👍 Approved. This looks great! Can't wait to see the draft!
