### ISSUE TITLE
hw3

### ISSUE THREAD

**Issue by Nawaf-Almansour** [fewd-puffin/final-project#17]
Website name : bird
WebSite idea: Interactive website provides news in a new way by displaying it in interactive boxes containing (text, image, video, voice).

if you put the mouse inside the box it will be active ,and its change a size and will display Media content.

https://imgur.com/a/sZLDtIs

**Comment by trevorpreston** [comment]
Hey Nawaf,

Looks like a big project, but I think you can do it!  Keep in mind that we won't be doing user authentication, so the login and signup features won't be doable with what we teach you.  Is that ok with you?

Approved!

**Comment by Nawaf-Almansour** [comment]
Thanks,
