### ISSUE TITLE
Discover Hail with Ahad

### ISSUE THREAD

**Issue by ahadalmu** [fewd-puffin/final-project#18]
https://www.figma.com/file/IP0anIDc67RVTMA8rOntbYqs/Untitled?node-id=9%3A100
the name of your website
Discover Hail .

what your website does?
Introduce Hail city.

who your website is for?

for every one has passion to discover a new places.

any predicted problems/ hard things you see/ things you need to learn!
I try to create a humbuger menu but I didn't manage it so the links to my wireframe not exist.

**Comment by trevorpreston** [comment]
Looks good!  Approved 👍
