### ISSUE TITLE
Muna project

### ISSUE THREAD

**Issue by muunakh** [fewd-puffin/final-project#19]
name of your website: Memo Card
what your website does:
A simple card matching game .
any predicted\ problem hard things you see:
It’s a big challenge for me I'll facing problems because that my first project, I hope it's doing well

**Comment by JackieCasper** [comment]
Hi Muna,
To do this you would need a backend which is not covered in FEWD. Anything to do with user data or storing information would need a server and database. Is there another idea you could submit for this project?

**Comment by muunakh** [comment]
![‏لقطة الشاشة 1440-08-09 في 1 57 30 ص](https://user-images.githubusercontent.com/49358681/56089920-03539400-5ea3-11e9-84e7-79b3b189eb0d.png)
![‏لقطة الشاشة 1440-08-09 في 10 48 42 ص](https://user-images.githubusercontent.com/49358681/56089921-077fb180-5ea3-11e9-9114-e280abbbcd58.png)

**Comment by muunakh** [comment]
![‏لقطة الشاشة 1440-08-09 في 10 48 42 ص](https://user-images.githubusercontent.com/49358681/56089934-254d1680-5ea3-11e9-8c74-6f8b20e4d8bb.png)
![‏لقطة الشاشة 1440-08-09 في 1 57 30 ص](https://user-images.githubusercontent.com/49358681/56089937-28e09d80-5ea3-11e9-8bc6-f3341d0dcbdf.png)

**Comment by muunakh** [comment]
.

**Comment by JackieCasper** [comment]
Approved 👍 👍  Looking forward to seeing it
