### ISSUE TITLE
Reem Final-project (Reminder by website or app)

### ISSUE THREAD

**Issue by REEMABDULAZIZ** [fewd-puffin/final-project#20]
name of website: Reminder by website or app

what your website dose: it is like serving to your self or any one to remind fo any thing or oppintment .
 
who your website is for:
any one can be use

links to your wireframe/prototype:
https://www.figma.com/file/DB4crz7u6k54HOX9xRAcUt4X/Untitled?node-id=0%3A1

any predicted problems/hard things you see/thing you still need to learn:
my proplem is I don't have time to more coloring or  more design but evry thing it's ok for me.thank you 

https://www.figma.com/file/DB4crz7u6k54HOX9xRAcUt4X/Untitled?node-id=0%3A1

**Comment by REEMABDULAZIZ** [comment]
thank you for every thing

**Comment by trevorpreston** [comment]
Hey Reem,

This sounds like a good idea, but in FEWD we won't be teaching the technology needed to send messages to the user.  Is there a version of this that you would like to do that does not involve messaging?

**Comment by REEMABDULAZIZ** [comment]
yes sure 
What do you think about this design 

https://www.figma.com/file/CEaAj2QJq8cti4sySP0uRhMd/Untitled?node-id=11%3A5

**Comment by trevorpreston** [comment]
looks good!  Approved 👍
