### ISSUE TITLE
Final project - My portfolio website - prototype.

### ISSUE THREAD

**Issue by AbdulazizDan** [fewd-puffin/final-project#21]
what it does: As a professional graphic designer, It's a personal website "portfolio".
For potential clients.
I have good experience for the Figma, so I didn't have any problem with it.

https://www.figma.com/file/0I2JmjA2jprCyZxaIxfZ8mlZ/Abdulaziz-Alhamdan's-portfolio?node-id=0%3A1

Thank you,

**Comment by trevorpreston** [comment]
Looks good!  Approved.

Keep in mind the the "contact us" box is going to require an API and could prove to be a big challenge for this project.  Just something to keep in mind, you may want to keep that feature as a "nice-to-have" if you have extra time.  V1 should probably not have that.

Approved!
