### ISSUE TITLE
Snake Game 

### ISSUE THREAD

**Issue by maramfhd** [fewd-puffin/final-project#3]
name of your website: Snake game 
what your website does: it is a game 
who your website is for: how missed the old games and Nokia lovers  
links to your waireframe: https://www.figma.com/file/OzvE61Ycto2gjr1BNtK2Q3NI/SNAKE-GAME?node-id=3%3A2
any predicted\ problem hard things you see: 
Maybe i'll facing problem with css and js but i believe on my self that i will successful and proud.

**Comment by trevorpreston** [comment]
Hey Maram,

I love the idea of doing a game, but snake is going to be too much for this project.  The challenges for this particular game are beyond the scope of this class and can take several weeks to develop. 

Some other games that have been successful for this project include Hangman ([the word-guessing game](https://www.youtube.com/watch?v=cGOeiQfjYPk)) , and [Tic-Tac-Toe](https://www.google.com/search?q=tic+tac+toe&safe=strict&source=lnms&tbm=isch&sa=X&ved=0ahUKEwj-v4DTuMjhAhUFWxoKHVLaBlgQ_AUIDigB&biw=1680&bih=971) (also called X's and O's).

Unfortunately we can't give approval for Snake.  Would you consider doing one of these?  There are some other ideas I am happy to discuss as well.  Let me know and we can get another idea approved this weekend!

**Comment by maramfhd** [comment]
thank you trevor for your support, i think i'll go with TicTacToe this is will be my wireframe
https://www.figma.com/file/Xb49eAZCwAeLumladZ1waXfl/TicTacToe?node-id=0%3A1

**Comment by trevorpreston** [comment]
excellent!  One thing with TicTacToe is to be sure that you aren't using tutorials.  As with everything, thinking through the problem yourself is an important part of the project.  Be sure to practice your javascript!  The logic is fun.  Looking forward to it!

**Comment by maramfhd** [comment]
hey Trevor, 

yesterday i was trying to finish my project to start study for my final exam on Saturday, so i find it some how the TicTacToe will be too long processes  if you allowed me to change my project to "To Do List" i find it simple, from last night i start working on it. if you give me the approve  i'll share with you. 

thank you.

**Comment by trevorpreston** [comment]
yeah that sounds good!  I think that's the right call, TicTacToe is a pretty big one.  Approved 👍

**Comment by maramfhd** [comment]
here is my wireframe
[here](https://www.figma.com/proto/EPaB1oYnsfK3xH1sQHd5nUL1/To-Do-List?node-id=0%3A1&scaling=min-zoom)
