### ISSUE TITLE
Saudi Mint and Coins

### ISSUE THREAD

**Issue by aaltwaim** [fewd-puffin/final-project#4]
name of your website: Saudi Mint and Coins

what is your website does:
	The website is to sell silver, gold and other old coins that are minted in Saudi Arabia and other countries. The coins will have its original certificate which shaw:
1- the type of materials it is made with
2- its purity.
3- the number of how many coins minted.

	it has the option to get a gift box for the coin if the customer want to send it to other people.
	
who your website is for
This site is for the coin collector or people who want to send a coin as a gift

links to your wireframe/prototypes

any predicted problems/ hard things you see/things you still need to learn

1-the design need some work to appear appealing to the customers
2- the might be more than 100 products which need a lot of pages
3 it is need to have a payment method on the site which need to be learned to add to my site.

[Saudi Mint (4).pdf](https://github.com/fewd-puffin/final-project/files/3065481/Saudi.Mint.4.pdf)
[Saudi Mint (3).pdf](https://github.com/fewd-puffin/final-project/files/3065482/Saudi.Mint.3.pdf)
[Saudi Mint (2).pdf](https://github.com/fewd-puffin/final-project/files/3065483/Saudi.Mint.2.pdf)
[Saudi Mint (1).pdf](https://github.com/fewd-puffin/final-project/files/3065484/Saudi.Mint.1.pdf)
[Saudi Mint.pdf](https://github.com/fewd-puffin/final-project/files/3065485/Saudi.Mint.pdf)

**Comment by trevorpreston** [comment]
👍 👍 approved!  This looks good.  Keep in mind that you won't be able to make users, so actually sending gifts or making posts won't be doable.  But if you keep this site as a coin-guide, you should be set for a great project.
