### ISSUE TITLE
Days Counter

### ISSUE THREAD

**Issue by emtenanh** [fewd-puffin/final-project#6]
name of your website: Days Counter.

 what your website does: The website will counts the days for any event you want.

who your website is for: for any person how wants to count remaining days or days since the event.

links to your wireframe/prototype: https://wireframe.cc/Ort3Nf

 any predicted problems/hard things you see/things you still need to learn:
-i think if we learn about java script  there will be no problems.
-The hard thing I will face is the layout .

**Comment by JackieCasper** [comment]
Approved 👍 👍 This looks great! Looking forward to seeing the draft!
