### ISSUE TITLE
J61

### ISSUE THREAD

**Issue by aljawharah61** [fewd-puffin/final-project#7]
name of your website:J61
what your website does:Its a profile from me 

who your website is for: the people who inters to get some of my knowledge
links to your wireframe/prototype:I have 2 choose plz help me to choose one 
1-
[https://xd.adobe.com/view/7d331b9f-5191-4620-70a9-70820e06fe83-0b02/](url)

2- 
[https://xd.adobe.com/view/101d609b-924c-492c-6e9b-b3043b828015-662c/](url)

**Comment by wahhab1404** [comment]
HI
links doesn't work for me 
it says "No results matched your search."
good luck.

**Comment by trevorpreston** [comment]
Approved! 

Jackie and I both agree that the first mockup (Pacman) is better, but we'll leave the choice to you.  Looking forward to it!
