### ISSUE TITLE
Explore Saudi Arabia Like never before

### ISSUE THREAD

**Issue by wahhab1404** [fewd-puffin/final-project#8]
Hi, 
The name of my website / app will be " Explore Saudi Arabia Like never before"
Prototype Link : [https://www.figma.com/proto/XAPhagpljNXv4aazpYPaLhd3/Cities?node-id=0%3A1&scaling=min-zoom](url) website will give information about some great places around Saudi Arabia that most of saudies and non-sauides doesn't know about them.
My website focus on people who like to go to interesting places and explore it to do different things in this short life.
I am getting a lot of difficulties in tow levels:

1. Gathering huge amount of information and pictures.

1. Codding the designe in my head will be a big challenge but I am ready for it :)

**Comment by wahhab1404** [comment]
Links Updated :)

**Comment by JackieCasper** [comment]
Hello!
👍 👍 Approved. This looks great! Something to think about though - there is a lot of content here. Try to think of a way to scale it down to start. Maybe making the pages for just one location first?
