### ISSUE TITLE
women on wheels

### ISSUE THREAD

**Issue by Amani40** [fewd-puffin/final-project#9]
name of website: women on wheels
what your website does:
To help woman who can not go to driving school to learn drive and she did not have time in mooring to do it. So the app/website offer to her driving instructor , place and time she want and like it. the app make learn car driving easy in flexible time
who your website is for:
women who want driving
links to your wireframe/prototype:
https://www.figma.com/file/NMaA9qm74cmEum1MaunZIMuT/Untitled?node-id=1%3A4

Image:
https://imgur.com/hZBiCF7
https://imgur.com/lVjH8Or
https://imgur.com/cDmtDaf
https://imgur.com/Pgm5XoK
https://imgur.com/r0DA98G
any predicted problems/hard things you see/things you still need to learn:

**Comment by trevorpreston** [comment]
Hey Amani,

These wireframes beautiful and the idea of connecting aspiring female drivers to instructors is a much-needed app.  The bad news is that this idea requires having a backend, which is not something  we are covering in FEWD.  Things like having users, setting up appointments, showing available instructors, etc. all requires a database.  I am truly sorry that this idea can't be approved - we just don't teach the tools needed to do it.  Is there anything you can think of to take this idea in a different direction?  One that doesn't require users, appointments, etc.

**Comment by Amani40** [comment]
I change my idea :( to :
name of website: My need
**what your website does:**
Helping persons to arrange their need in life by some Categories   .In the app, user write a list of what she/he need from Category as like grocery or pharmacy. The app is helping person saves the list of each Categories and she/he can also edit it. This application looks like the memo but in a different way.
who your website is for:
any one
links to your wireframe/prototype:
https://www.figma.com/file/OLbKpQ7MeTTeAOvOObnWNeSi/Untitled?node-id=15%3A24

**Comment by trevorpreston** [comment]
Looks good!  Keep in mind this would usually be done by saving data in a database, which we won't be doing in FEWD.  But you might be able to get around this with a handy front-end browser tool called [local storage](https://www.w3schools.com/jsref/prop_win_localstorage.asp).  Take a look and see if this is something you want to do.

Approved if this looks good to you!
